### ISSUE TITLE
flask.ext.assets not found

### ISSUE THREAD

**Issue by thewhitetulip** [hasgeek/hasjob#103]
Whenerve I am trying to execute the hasjob portal on my local machine I am getting this error, can anyone please explain the problem my machine is having? Do I need to install the latest Flask version? I have Flask 0.10.1 installed along with all the other dependencies as per requirements.txt

raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.assets

also is there any plans for making a release version?

**Comment by jace** [comment]
Missed responding to this. There are no release versions of Hasjob as there is only one deployment of the site and the `master` branch is considered the current stable release.

**Comment by thewhitetulip** [comment]
Okay
