### ISSUE TITLE
In-page reloading of content

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#107]
Related to #106, all links within Hasjob reload the full page. This makes it difficult to build interactive filtering as every filter will trigger a reload. We should switch to a dynamically rendered content area, replacing it on every click and updating the URL with History.js or similar.

**Related:** the homepage renders a stickie for all active jobs on load. This is currently 700+ jobs, making the page rather heavy on mobile. The homepage should load only the last 24 hours worth of jobs statically (primarily for search bots) and load the rest in JS using an infinite scroll plugin, so that mobile rendering gets snappier.

**Comment by shreyas-satish** [comment]
Infinite scroll added in https://github.com/hasgeek/hasjob/commit/55316a3244ff7d6f33d3dc2566a3c4ed2ee409c5
