### ISSUE TITLE
Need a way to shortlist/save job for future use

### ISSUE THREAD

**Issue by sachugit** [hasgeek/hasjob#108]
For a logged in user there should be a way to save a job for future reference.

Also need not to mention that need a way to brows all shortlisted/saved jobs (by date).

**Comment by jace** [comment]
Posts can be saved as of 302135dc1c8a0f738deb9cc5e73e652e73a33417. Viewing interface forthcoming.

**Comment by jace** [comment]
@sachugit Have you seen the feature? Does this do what you want?

**Comment by jace** [comment]
Fixed in #276.
