### ISSUE TITLE
Replace grouped cards with single cards?

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/hasjob#121]
Couple of issues with grouped cards:

1. It takes two clicks to get to the job page (with both, the earlier method of showing all the jobs posted by the respective company and the current method of expanding the cards inline). 

2. I may miss a job because it's beneath a job card that I may not be interested in. Let's say I'm looking for an Android development job. I now may miss the Android job posting by Brewery Labs, because it's 'hidden' under an iOS job posting (which I'm unlikely to click).

Should we instead show individual cards, redirect directly to the job page, and have 2 sections on a job 'show' page; one for 'other jobs posted by the same company' and one for 'related jobs'?

**Comment by jace** [comment]
Closing this since there's been no action item in months.
