### ISSUE TITLE
Simplify application management

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/hasjob#136]
**Problem**
Currently, the 'view candidates' page, shows one application and the rest as a list on the side. As an employer, clicking on every application to process it, feels like too much work. This is especially the case when there is a long list and when most applications only have a link to a resume or consist of a short paragraph.

**Suggestion**
Make it easy to scan through the list (via scrolling) and allow an employer to apply bulk actions to applications (reject, respond with similar message). This would also make it easier to process the applications on mobile.

**Data**
[User research](http://uxmyths.com/post/654047943/myth-people-dont-scroll) seems to suggest that users prefer scrolling to clicking.

**Challenges**
How can we let employers share the URL to a particular application? By showing a permalink beneath each application.

**Test Metric**
On average, what is the % change in the number of applications processed per day?

**Comment by jace** [comment]
Don't forget the average job has 0-5 candidates and the submission is also in email. Most employers never come back to Hasjob to process the submissions (proof: the number of applications still in the New status, indicating never visited).

**Comment by shreyas-satish** [comment]
Closing for now.
