### ISSUE TITLE
Reduce number of fonts used

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#152]
Hasjob currently loads four fonts:

1. Fira Sans for body text
2. McLaren for stickies
3. Walter Turncoat for stickie annotations
4. Source Sans Pro for the network bar

The last is a complete waste and should be eliminated immediately since the networkbar is itself deprecated.

The third is underused and should be replaced with a smallcaps/uppercase version of the second. This is especially for embedded use where the font will slow down a third party site rendering.

**Comment by vidya-ram** [comment]
Fixed in  #191
