### ISSUE TITLE
Can't repost withdrawn job

### ISSUE THREAD

**Issue by adityar7** [hasgeek/hasjob#156]
I posted a job on Hasjob and immediately withdrew it as I wanted to change the email address for receiving applications, which I think was allowed earlier.

Now I'm unable to create the same job due to the restriction of posting a similar job within 30 days.

**Comment by jace** [comment]
You can only change the email address before it's confirmed. If you have the URL to the (withdrawn) job however, we can restore it.

**Comment by adityar7** [comment]
I think this is it: https://hasjob.co/instahyre.com/clsav/

Ideally I would be able to post this job with a different email address but otherwise if you could restore it, that would be great, thanks.

**Comment by jace** [comment]
It's restored. Can you mail us at support@hasgeek.com with the email address you want to use? We'll change and bump it back to the top.
