### ISSUE TITLE
Filters should filter themselves

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#172]
To implement user friendly faceted search, the filters should also filter themselves. Selecting a "Freelance" job type, for instance, should remove all locations and categories where Freelance jobs are not available.

**Comment by shreyas-satish** [comment]
So, the interdependence of filters would be limited between locations, categories and types? Or should this extend to include pay and keywords as well? For instance, would entering 'python' result in the other filters being refreshed?

**Comment by jace** [comment]
Yes, all of them should be interdependent.
