### ISSUE TITLE
Starring jobs accidentally

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#186]
Job starring is being mysteriously triggered without user interaction. Here's an example where I did not star *any* of these jobs:

![screen_shot_2015-03-24_at_12_18_08_am](https://cloud.githubusercontent.com/assets/26695/6787880/b8ade90a-d1bb-11e4-9ad3-b0b30cf263e7.png)

Possible causes:

1. Accidental finger touches on stickie corners (unlikely)
2. Something in the way click events are registered that causes them to be triggered (likely since the `created_at` timestamp indicates many jobs being starred together).

**Comment by shreyas-satish** [comment]
Fixed in 90ba77a10b1364526e149d764b40ff9ae21e4bcc.
