### ISSUE TITLE
Location selection dropdown problem

### ISSUE THREAD

**Issue by jitendravyas** [hasgeek/hasjob#195]
in current form, in small viewport, it's problematic. I can't see locations below the fold, when I scroll down  dropdown disappears

![hasjob 2015-05-23 12-13-36](https://cloud.githubusercontent.com/assets/77309/7782747/52c0a86c-0145-11e5-8c17-4d17a3cfe557.png)

**Comment by shreyas-satish** [comment]
Fixed in https://github.com/hasgeek/hasjob/pull/196. Thanks for reporting.

**Comment by jace** [comment]
Sorry this took so long. We were more interested in hammocks and badminton while at Hillhacks. :)
