### ISSUE TITLE
When someone tried to star a job "TypeError: argument of type ‘AppenderBaseQuery’ is not utterable"

### ISSUE THREAD

**Issue by sindhus** [hasgeek/hasjob#234]
Recently we received an exception email when someone tried to star a job post they posted. It didn't work for them the first time and hence this email was sent to us. 

After inspecting the DB tables against the job post hashid in "starred_jobs" and "jobpost" and "user" tables, we know for sure that it worked second time around for the person (that is, they were able to successfully bookmark the job post)

The first few lines of the exception email are here:

```
Exception on /star/snbvb [POST] Traceback (most recent call last):

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
  response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
  rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
  reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
  rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/home/hasgeek/dependencies/flask-lastuser/flask_lastuser/__init__.py", line 372, in decorated_function
  return f(*args, **kwargs)
File "./hasjob/views/listing.py", line 200, in starjob
  if post in g.user.starred_jobs:
TypeError: argument of type ‘AppenderBaseQuery’ is not iterable

Frame _call_ in /usr/local/lib/python2.7/dist-packages/flask/app.py at line 1836
```

[Line 200](https://github.com/hasgeek/hasjob/blob/master/hasjob/views/listing.py#L200) where the exception occurred contains logic for bookmarking/starring a job post. The logic contained in the while loop deals with two things: 
1. user trying to bookmark a job post
2. the user double clicking to bookmark a job post

Using the shell.py in Hasjob (run it with `python shell.py`, init_for("dev")), it was verified that starred jobs belonging to a user is object of type sqlalchemy.orm.dynamic.AppenderBaseQuery and it's class is sqlalchemy.orm.dynamic.AppenderBaseQuery. This class is indeed iteratable even if the user doesn't have any starred jobs. 

```
➜  hasjob git:(staring-exception) python shell.py 
>>> init_for("dev")
>>> models.User
<class 'hasjob.models.user.User'>
>>> u = models.User.get('nigelbabu')
>>> for j in u.starred_jobs: print j
... 
```

Going through SQLalchemy's [source for sqlalchemy.orm.dynamic](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/orm/dynamic.py) didn't lead to anything because the class is not defined there.

**Comment by jace** [comment]
Closing as it hasn't been reproducible.
