### ISSUE TITLE
Remove milliseconds from user activity records

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#243]
As a result of #232 and #233, we index datetime columns on tables with a large number of entries. These indexes are potentially oversized because they index to the millisecond level, but milliseconds are unnecessary in our use case. No more than minute-level precision is required in reports, but in at least one query that does a timestamp comparison (job session impression <= job session view; for A/B testing conversion vs external link), second-level precision is necessary.

Since it's not practical to index without milliseconds and query specifically against the index, we could instead drop milliseconds from the row when writing to the database.

1. The `datetime.utcnow` that we use could be replaced with a custom function that strips out milliseconds.
2. Alternatively, we could write a SQLAlchemy func handler that returns (1) or `NOW()::TIMESTAMPTZ(0) AT TIME ZONE 'UTC'` if the database is detected to be PostgreSQL.
3. Because #233 already indexed datetime, we need to update existing records by stripping out milliseconds. However, because #233 isn't yet in production, maybe we could update the migration and take it to production all at once.

**Comment by jace** [comment]
All of this is premised on indexes being inefficient with millisecond precision, which needs to be confirmed. @karthikb351?

**Comment by sindhus** [comment]
@arunkrishnan do you want to take a stab at this? The 1 and 2 are easily doable.

**Comment by arunkrishnan** [comment]
Yes, I'll work on it.

**Comment by jace** [comment]
I haven't found any evidence yet that milliseconds/microseconds are a problem. No results when I search for it. Maybe we have to construct a test db and see if it's real?

**Comment by jace** [comment]
@arunkrishnan Any update? We're looking for evidence that milliseconds are a problem for the index.

**Comment by arunkrishnan** [comment]
I couldn't find any evidence either. But to be on the safer side, should we trim down the milliseconds, anyway?

**Comment by jace** [comment]
No, no point losing millisecond data if there's no clear upside. @karthikb351, this was your idea. Please provide evidence.

**Comment by jace** [comment]
Closing because there's no evidence brought forward so far. @karthikb351
