### ISSUE TITLE
Instant refresh should register a new pageview in Google Analytics

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#254]
When the URL changes, that is a new pageview and should be registered as such in Google Analytics.

**Comment by shreyas-satish** [comment]
Fixed in https://github.com/hasgeek/hasjob/commit/b24e5ecfdf5b3b4c1c20fbed45308907cd207930. Ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
