### ISSUE TITLE
Loading more button should be disabled

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#287]
On Hasjob's home page, the "Load more" button automatically starts loading and changes to "Loading more...". The button is supposed to be disabled in the loading state, but isn't.

<img width="322" alt="screen_shot_2016-01-31_at_12_00_43_am" src="https://cloud.githubusercontent.com/assets/26695/12697595/f96d38f4-c7ad-11e5-87c6-53494f55b1ee.png">

**Comment by shreyas-satish** [comment]
Fixed in https://github.com/hasgeek/hasjob/commit/40be4d971059c5965ce86ce70d4a76b3172d5e40
