### ISSUE TITLE
/in/<location> no longer works

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#301]
The `/in/<location>` endpoint displayed jobs in that location _and_ a description of that location if there was a corresponding `Location` entry.

Since the site now redirects to `/?l=<location>`, the description is never shown. This unfortunately breaks an SEO optimisation. The location description must be shown, or the old URL must continue to exist.

**Comment by iambibhas** [comment]
@jace on the site, I can visit https://hasjob.co/in/bangalore but locally, it gets redirected to `?l=bangalore`. How is that?

**Comment by jace** [comment]
@iambibhas Locations can have landing pages. Go to `/location/new` to make one.
