### ISSUE TITLE
Filter URLs don't populate filters

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#302]
When a URL like https://hasjob.co/?q=python is loaded, the Keywords box isn't automatically populated with the search term. It should be.

**Comment by jace** [comment]
The pay slider has this problem too. Consider this URL: https://hasjob.co/?l=bangalore&t=fulltime&c=programming&currency=INR&pmin=0&pmax=10000000&q=python

**Comment by jace** [comment]
Pending edge case from #301. When on a location page like `/in/bangalore`, the Location dropdown isn't populated.

**Comment by iambibhas** [comment]
@jace for that pending case, I think if we set the location filter in the backend for urls like `/in/<location>`, that should be enough? Then the location value should be set just like it does for `?l=<location>`. 
@shreyas-satish can you point me where the filters are set in the backend? I've looked into setting `data_filters` inside `index()` view, but that doesn't seem to be working. Can you help?

**Comment by jace** [comment]
@iambibhas the `/in/<location>` URLs are only for SEO and so only the important destinations are covered (although we should cover a large list). As soon as you change the filters the URL changes to `?l=<location>`

**Comment by jace** [comment]
The filters code is very crude and the JS code at various points reads them directly from the URL. We need a filter state framework.
