### ISSUE TITLE
Dynamic refresh for search query should be disabled

### ISSUE THREAD

**Issue by sam95** [hasgeek/hasjob#312]
The search query should be taken only after the click of enter key. Suppose I try to enter a word `fresher` in the search bar. Each character is searched as soon as I type it on the textbox, The website doesn't wait until I type the query completely.

**Comment by jace** [comment]
Hitting Enter isn't always intuitive.

Sounds like we just need a longer delay (or space or enter characters) before we refresh as @sam95 is right in that mid-word refresh isn't useful: we only search for "keyword", not "keyword*". This may also reduce load from too-frequent refreshes on the server.
