### ISSUE TITLE
inject_filter_options is added to template context even when not needed

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#317]
In [`hasjob.views.helper.inject_filter_options`](https://github.com/hasgeek/hasjob/blob/be39bcd50f1a085540732446fe82df1c3302febd/hasjob/views/helper.py#L767-L781), as an app context processor, it's called for every single query whether it's needed or not. Rather than insert actual values, it should insert functions which the template can call when needed.

**Comment by iambibhas** [comment]
The issue with inserting functions is that cache can't be set. It can't pickle function objects.

**Comment by jace** [comment]
Fair point, so let's have the outer function return an inner function, which hits cache. Rather than return a dict of `job_location_filters`, `job_type_filters` and `job_category_filters`, we return a dict with a single key, `job_filters`, which is a function that when called returns another dict with the above three keys.

The templates will have to be updated accordingly.

**Comment by iambibhas** [comment]
But the values of `job_filters` will still be a function, right? Which will raise the same issue?

**Comment by jace** [comment]
No, it will be actual values.
