### ISSUE TITLE
Catch large file upload client side

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#320]
When an employer attempts uploading a very large logo image file, Nginx errors out with HTTP 413 (hasgeek/hasdev#6). This can be prevented on the client side with JS-based validation of the file input's payload size.

**Comment by sindhus** [comment]
there seems to be stubbed out code for this https://github.com/hasgeek/hasjob/blame/master/hasjob/forms/jobpost.py#L109

**Comment by jace** [comment]
That is not client-side.
