### ISSUE TITLE
If you don't select any filter then it will keep showing up with scrolling down

### ISSUE THREAD

**Issue by HemantPawar** [hasgeek/hasjob#324]
1) Don't select any filter
2) Scroll down

<img width="1280" alt="screen shot 2016-04-25 at 12 53 35 pm" src="https://cloud.githubusercontent.com/assets/471327/14776552/ca7b6406-0ae4-11e6-87c2-258026f7ab8c.png">

**Comment by jace** [comment]
Thanks for reporting. A bit embarrassed this slipped through.
