### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by HemantPawar** [hasgeek/hasjob#345]
I'm getting 504 Gateway Time-out pages very frequently from past one month. I believe there is some serious issue with HasJob server setup.

Try to open 3-4 tabs together and a very good chance is that you will get a 504 Gateway Time-out page.

**Comment by jace** [comment]
Closing this ticket since it's a known issue being tracked elsewhere, but is not relevant to the code, which this repository is about.
