### ISSUE TITLE
For one-time payment specification in a job post, <50k is not accepted

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#346]
The form accepts ranges in 50k increments only. It should be possible for a user to either:

1. Have more granularity when specifying one-time payments, or
2. Allow a user to enter any number and don't reset it when they leave the field

**Comment by iambibhas** [comment]
While we're on this, just wanted to ask, why isn't INR selected as the default currency? I really didn't notice the currency radios the first time and was wondering why isn't it showing Rupee symbol.

**Comment by jace** [comment]
No good reason actually. Was thinking of not biasing users by pre-selecting, but to be honest Hasjob is 99% Indian employers anyway.

**Comment by iambibhas** [comment]
> Have more granularity when specifying one-time payments

With a range like 0-100,00,000, it's really hard to be more precise using a slider. If we lowered the upper limit to, say, 4-5 lakh, we could give an increment of 5000 maybe.

**Comment by jace** [comment]
The only reason the slider values are the same no matter what options you select (recurrance and currency) is because I didn't know enough JS to do better. Each combo could have its own set of values.

**Comment by jace** [comment]
[Here's where the increments are defined](https://github.com/hasgeek/hasjob/blob/b46109e498a8d81d8eef812fbd14ed96f6e2f817/hasjob/views/helper.py#L411-L453).

**Comment by iambibhas** [comment]
@jace why are the limits and increments defined in the backend? Couldn't this be done easily with JS? Backend could just take min and max and validate that.

**Comment by iambibhas** [comment]
@jace oh wait, I think the increments are here - https://github.com/hasgeek/hasjob/blob/a7e8a4c769963a0877359297c5661b240c34b310/hasjob/static/js/app.js#L560 ?
