### ISSUE TITLE
In jobpost view, move charts into a separate request to reduce initial load time

### ISSUE THREAD

**Issue by jace** [hasgeek/hasjob#347]
Charts aren't needed for the average view, so rendering them in the main request slows down the request. They should be loaded in a secondary request.

**Comment by iambibhas** [comment]
@jace what decides if the chart should be loaded? I'm assuming you mean the pay graph here. Is there any other chart?

**Comment by iambibhas** [comment]
- move the impression chart to a separate section below tags
- generate the chart using c3
- load the chart in a separate request, like related posts
