### ISSUE TITLE
Don't auto-fill email addresses when posting new jobs

### ISSUE THREAD

**Issue by clay-to-n** [hasgeek/hasjob#378]
When filling out a job posting, it auto-fills the job's email address with your account's email address.

I was creating a job from my name@company address (what I typically sign up for services with), but I intended to send the job applicants to the careers@company address.  Once the post is up, I can't change the email address, so this is frustrating.

Pre-filling is often nice, but I worry for a job board a sizable amount of users will want their account to use a different email address than their job posts.  Especially since email isn't changeable (yet), I think removing the auto-fill for this field would reduce user error.

**Comment by jace** [comment]
Good catch. Will remove the auto-fill. It's also a problem when the autofill goes to a gmail account, which we no longer allow in a post.
