### ISSUE TITLE
Hasjob widget

### ISSUE THREAD

**Issue by vidya-ram** [hasgeek/hasjob#454]
A Hasjob widget that can be embedded on any third party website to imports jobs and display them using a default stylesheet provided by the widget.
It should be trivial to embed the widget on website, as simple as adding a script tag to load the widget (jobs and stylesheet) and one container tag (a div) to include the widget on the page.

Points to be considered:

1. Loading external CSS and JS on the site bypassing browser's single origin policy. This could be solved by using JSONP.
2. On loading Hasjob stylesheet, conflict with the website stylesheet.
3. Maintenance, in case we change styles of the stickies but the third party has also customised styles for their embed.

**Comment by jace** [comment]
Shadow DOM is useful here, if it's supported at all anymore (I recall Safari was strongly against it).

We could host the widget in a container that has a comprehensive CSS reset for all elements within it.

**Comment by jace** [comment]
We could also use an iframe that automatically adjusts height to match the contents (using JS). This will make it hard to use features like grouped stickies, where the frame's height changes during interaction, but that may be an acceptable compromise for embeds (no grouping).

**Comment by vidya-ram** [comment]
We could use an iframe but what functionalities are we looking at? Do we want some to view the job post details from the iframe or come to hasjob to view and apply?

**Comment by jace** [comment]
The user has to move to Hasjob for all further interaction (for now).
