### ISSUE TITLE
Database Access 

### ISSUE THREAD

**Issue by hallidude** [hasgeek/hasjob#46]
A front end user interface that can pull out data about HasJob is required. 
The data parameters required are 
1. Name of the company that has posted a Job on HasJob 
2. Category/Job Title(s) (This could be a little vague in terms of data. What is an important metric is the kind of group the Job belongs to. By group I mean cloud, JS etc. Here's an example: http://jobs.hasgeek.com/search?q=cloud 
   It would be good to have all the companies that show up on this search result as a list with the mentioned parameters. The Category might not be adequately able to tell us about the job) 
3. Contact of the Job Poster 
   Email/Phone number)
4. City of the Job/ Office
   We will most probably only have the city where the job requirement is. It can be safely assumed that the comany has an office at the site specified. 
5. Company Url

The HasJob database can be used to coordinate the marketing and sponsorship activities. This is a good approach to take as users on the list already know of Hasgeek and will be open to exploring sponsorship options with us. 

This feature can be further extended in the future to include a company's cumulative activity data on Hasgeek products and events, a part of the larger Hasgeek profile building activity

**Comment by jace** [comment]
Deprecated by #380.
