### ISSUE TITLE
Failing to install Flask-Babelhg

### ISSUE THREAD

**Issue by salimsaid** [hasgeek/hasjob#559]
When i try to install requirements with `pip install -r requirements.txt` , i get below message

`ERROR: Could not find a version that satisfies the requirement Flask-Babelhg (from Flask-Lastuser==0.4.1.dev0->-r requirements.txt (line 29)) (from versions: none)
ERROR: No matching distribution found for Flask-Babelhg (from Flask-Lastuser==0.4.1.dev`

Am running python 3.8.0 

I was running python 2.7 but i upgraded because `Pillow==7.0.0` requires python 3^ .

**Comment by jace** [comment]
Install directly from the Git repo: https://github.com/hasgeek/flask-babelhg

We forked because upstream was not well maintained.

**Comment by jace** [comment]
Assuming this is resolved. Please re-open if you need further assistance.
