### ISSUE TITLE
Site is timing out

### ISSUE THREAD

**Issue by astriskit** [hasgeek/hasjob#572]
Hi there, 

The site is timing out when clicked on an individual "yellow-card" - 
![hasjob-time-out](https://user-images.githubusercontent.com/28564247/90216998-add42200-de1d-11ea-9c32-eed91d0cbbb3.png)

btw, thanks for the nice-product/job-board !!

**Comment by astriskit** [comment]
sorted out

**Comment by iambibhas** [comment]
@astriskit thanks for the report. We got it fixed. :blush:
