### ISSUE TITLE
Some URLs are missing a character

### ISSUE THREAD

**Issue by asdofindia** [hasgeek/hasjob#625]
Eg: 
![image](https://user-images.githubusercontent.com/945777/129924421-8c6e4ef9-1658-4703-afec-8ad83a13d866.png)
https://hasjob.co/whitehatjr.com/7zgax - See the `hitehatjr.com` in the header

Similarly, https://hasjob.co/weqtechnologies.com/gnho9 has become eqtechnologies

I looked at the `cleanurl` function but that seems correct to me. Can't figure out who is off by one and why.

**Comment by jace** [comment]
We rewrote the cleanurl filter to be a bit more robust, put it in the shared library, and goofed up on `lstrip`, which takes characters, not substrings. It was failing on URLs that begin with `w`, but the tests only had variations of `example.com` URLs. Fixed it there.
