### ISSUE TITLE
Pay range is not visible to job seekers.

### ISSUE THREAD

**Issue by astriskit** [hasgeek/hasjob#759]
Job post have no pay range visible, but it is/was added per se the person posting the [job](https://hasjob.co/doormonk.in/mqd33). It should be visible to the job seeker too!! 

On the main branch - line [here](https://github.com/hasgeek/hasjob/blob/b8ec2db79b7973182d567da3d8b841a216bfdcbe/hasjob/templates/detail.html.jinja2#L231).

**Comment by jace** [comment]
This is intended: candidates can filter by pay range, but can't see the pay range on the job itself. We found candidates tend to anchor on the top-end of the pay range.

**Comment by astriskit** [comment]
That's understandable - but seemingly the posters do not know that the pay
range isn't visible to job seekers. It would be great to show a little
notice/info about the same along the side of it.

**Comment by jace** [comment]
<img width="915" alt="Pay range widget" src="https://github.com/hasgeek/hasjob/assets/26695/2df34cd1-08e5-48d8-90a6-728c56804388">

The notice is already present ^

**Comment by astriskit** [comment]
Cool. Thank you.
